# -*- coding: utf-8 -*-
"""Assignment-009/7 (Fizz Buzz Numbers)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G950gJh4xmLmTZXp2CReD_HxqmwpdF2N
"""

for fizzbuzz in range (100):
  if fizzbuzz % 3 == 0 and fizzbuzz % 5 == 0:
      print('fizzbuzz')
      continue
  elif fizzbuzz % 3 == 0:
      print('fizz')
      continue
  elif fizzbuzz % 5 == 0:
      print('buzz')
      continue
  print(fizzbuzz)

